services:
  postgres:
    image: postgres:${POSTGRES_IMAGE_VERSION:-latest}
    environment:
      - POSTGRES_DB=${IMPRO_BIDULE_DATABASE_NAME}
      - POSTGRES_USER=${IMPRO_BIDULE_DATABASE_USER}
      - POSTGRES_PASSWORD=${IMPRO_BIDULE_DATABASE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 20s
      retries: 3

  application:
    image: ghcr.io/nortalle/impro-bidule:${IMPRO_BIDULE_IMAGE_VERSION:-latest}
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      # Traefik
      - traefik.enable=true
      # Middlewares
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
      # HTTP
      - traefik.http.routers.application-external-http.rule=Host(`${WEBSITE_FQDN}`)
      - traefik.http.routers.application-external-http.entrypoints=web
      - traefik.http.routers.application-external-http.middlewares=redirect-to-https
      - traefik.http.routers.application-external-http.service=application
      # HTTPS
      - traefik.http.routers.application-external-https.rule=Host(`${WEBSITE_FQDN}`)
      - traefik.http.routers.application-external-https.entrypoints=websecure
      - traefik.http.routers.application-external-https.tls=true
      - traefik.http.routers.application-external-https.tls.certresolver=letsencrypt
      - traefik.http.routers.application-external-https.service=application
      # Service
      - traefik.http.services.application.loadbalancer.server.port=3000

  traefik:
    env_file:
      - .env
    image: traefik:${TRAEFIK_IMAGE_VERSION:-latest}
    command:
      # Global
      - --log.level=ERROR
      - --api=true
      # Docker
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.exposedByDefault=false
      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Certificates
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=vincent.guidoux@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/etc/traefik/acme.json
    labels:
      # Traefik
      - traefik.enable=true
      # Middlewares
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
